apiVersion: v1
kind: Service
metadata:
  name: tracedata-frontend-service
  namespace: tracedata
  labels:
    app: tracedata-frontend
    tier: frontend
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: tracedata-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
