apiVersion: v1
kind: ConfigMap
metadata:
  name: tracedata-sentiment-worker-config
  namespace: tracedata
  labels:
    app: tracedata-sentiment-worker
    tier: worker
    environment: prod
data:
  APP_ENV: "production"
  DEBUG: "false"
  PYTHONPATH: "/app"
  DATABASE_URL: "postgresql+asyncpg://tracedatauser:CHANGE_ME_BEFORE_DEPLOY@tracedata-db-service.tracedata.svc.cluster.local:5432/tracedata"
  REDIS_URL: "redis://tracedata-redis-service.tracedata.svc.cluster.local:6379/0"
  LOG_LEVEL: "INFO"
