apiVersion: v1
kind: Service
metadata:
  name: tracedata-api-service
  namespace: tracedata
  labels:
    app: tracedata-api
    tier: backend
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: tracedata-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
