{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "tracedata.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
{{- end }}
