apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tracedata-cluster-secrets
spec:
  # Example for AWS Secrets Manager. Replace with your provider.
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-manager-credentials
            key: access-key-id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-secrets-manager-credentials
            key: secret-access-key
            namespace: external-secrets
