apiVersion: v1
kind: ConfigMap
metadata:
  name: tracedata-db-config
  namespace: tracedata
  labels:
    app: tracedata-db
    tier: database
    environment: prod
data:
  POSTGRES_DB: tracedata
  PGDATA: /var/lib/postgresql/data/pgdata
