apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracedata-db-pvc
  namespace: tracedata
  labels:
    app: tracedata-db
    tier: database
    environment: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
