---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tracedata-db-secret
  namespace: tracedata
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBSUeuJHulJLykZag0x+BXoZL/XEtuBnkbxADKptapz+ogjN/zPJFVTeJtlNtE4xKKmAQvZnk0JUu22t1GCecfqVvQNkywutSCqHmaOcGtYwHZrcOUmR3jjaJxNY8jYhoFGFgvSq8H5KhgPud7rKgNDkKn7lOSBY9MzYn1RQiO2nCfE2VGfP+j/1Qz9vXBqelDAuKp4M2qkuSk2W6gib2uzOQlgxYhkFTwqvdnRFUWFd1CtawG5wct/Gt6XWQwWrFB6Fnf851qXIz6vrkjS2JeI2wjfatnp7NY9LqBEtek6fP1s3o98jY1g8x8FZDrGkysBj1VYdAOtI9fqYpz2ttsZ9P5RT1Ux1idPgwtpNXdpzv/LtmLJ2yiFlWafMOqv+9FaqLw4qR2Sv9Sxum5h3ogpZIVeQWsxT6xkP6w2ijpuIlzD0k4N/pvrgTDskxhmNBIx+gzUoxDku1V9GBm0SaPE0gNiqFGH3UxfCH/saN8Kf2Cq4N66aEdohdXGfpboK4EBDf/JffaERyOp6zR/z+hrryzRMwGiwtjj2o7M8JikAr9qNqHY8lsrSU7jNX3l0fiTWF/agyXKQ7ieHrWBhZw7ZqrM110EtVmsLKZHXFgQdegYSfFdjRKgvT9JmTbnc4Y2OUZ1r3ZZAKoflvLhJEwI6bEbH24zh8xmm4SGax7dQnrPiPmaNW/RIQBAnwGwe4gw6Ik9IDfEe2QiLq3SjXJBHA==
    POSTGRES_USER: AgA1HQwzu4gRHs3yvDYp32Qr7JFTO8iVlQIciujAhA4yiJip2aNmG/xDB/76+z/5e8QB+tFk1P5Y3eVSl8WDNSgovQaHxFRnqXlq+ucN3CBgSs2TK76z1+N6shDgOwth0Cf8Wha+1/cqIZTg46x9/7QrtcDdmSuatZE3HmRryD/rDuS9WPBwoUHBzX28Hd0Q6kyZAN/drJZGH9zJKyU015Zw0sFU/+zU9mCVpnERhi3fzzgpdBBbb+C98NxFvDyE44NCxA9mHtbW6aCMq4yfZKdWqG3A2OjParWh9QahohmMOctrMcnqPY4GHHmscV/IskReKqRwFhZBE/ajRppgq7Se7ShNCXAPSKqSG+2rJ9p3MCiK52pzZw3Mpnl+v1d2D8PFMmFPYEZdOuMaTUPqnACDuFIXEu0WAt2ABAvs/vcOs9tcX6k6zOjmF+B31HKyJLud5eHIaX33E2WrqYNAHnJT2sjSiSt2YgdAS1TUm4cXB0BeTD10jLscCdVPtb/NYoVafAvDvVnDETuv27dE8ynejGAPgTXUubJ05N8pmEYsV06arqxF9obrskjwfBzZ4nE7exrMMYWGdr41ZpSgxMS9/Cjh/WbMhC4hVzjwYsxRkNfZyCO7nvVVaESMqCyRdvjzfka9+hGHLeeDBymII/+EMaF7l6VqhvwCJsXoCQutiw4RKdZ/M/wVJkPdJ15/nuhBlzJIl7uE3/ir44BJ
  template:
    metadata:
      labels:
        app: tracedata-db
        environment: prod
        tier: database
      name: tracedata-db-secret
      namespace: tracedata
    type: Opaque
