apiVersion: v1
kind: Service
metadata:
  name: tracedata-db-service
  namespace: tracedata
  labels:
    app: tracedata-db
    tier: database
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: tracedata-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
