apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Run ArgoCD server in HTTP mode so nginx ingress can terminate TLS
  server.insecure: "true"
