apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracedata-sentiment-worker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/tracedata-ai/tracedata-ai-monorepo.git
    targetRevision: feature/TDATA-96-DO-K8s
    path: k8s/tracedata-sentiment-worker

  destination:
    server: https://kubernetes.default.svc
    namespace: tracedata

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
