apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.12.0
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
        singleBinary:
          replicas: 1
        monitoring:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
