apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracedata-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.20
    helm:
      values: |
        auth:
          database: tracedata
          username: tracedata
          existingSecret: tracedata-postgres-auth
        primary:
          persistence:
            enabled: true
            size: 20Gi
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: tracedata-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
