apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracedata-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.6.4
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: true
          existingSecret: tracedata-redis-auth
        master:
          persistence:
            enabled: true
            size: 8Gi
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: tracedata-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
